# Generated by Django 6.0.6 on 2026-06-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='category',
            field=models.CharField(default='Prayer', max_length=100),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='pray_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leader',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='leadership/'),
        ),
    ]
