# Generated by Django 6.0.6 on 2026-06-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prayerrequest_category_prayerrequest_pray_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='achievements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
