# Generated by Django 6.0.6 on 2026-06-10 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mentor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comments',
        ),
        migrations.AddField(
            model_name='alumni',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leader',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='leader',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='X (Twitter) URL'),
        ),
        migrations.AddField(
            model_name='leader',
            name='whatsapp_url',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp Link (wa.me)'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='X (Twitter) URL'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='whatsapp_url',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp Link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='member_type',
            field=models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni'), ('online', 'Online Member')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
