# Generated by Django 6.0.6 on 2026-06-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_blog_comments_alumni_user_leader_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
    ]
