# Generated by Django 6.0.6 on 2026-06-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='leader',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Uncheck to move to Past Excos'),
        ),
        migrations.AddField(
            model_name='leader',
            name='tenure',
            field=models.CharField(default='2024/2025', help_text='Group year (e.g. 2023/2024)', max_length=50),
        ),
    ]
