# Generated by Django 6.0.6 on 2026-06-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_blog_image_leader_is_current_leader_tenure'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Testimony', 'Testimony'), ('Teaching', 'Teaching'), ('News', 'News'), ('Event', 'Event')], default='News', max_length=50),
        ),
    ]
